# Generated by Django 5.1.3 on 2024-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ima')),
                ('janr', models.CharField(choices=[('horужс', 'Horror'), ('sciдля задротов', 'Sci'), ('artРумата', 'Arthouse')], max_length=100, verbose_name='janr')),
                ('year', models.IntegerField()),
                ('discr', models.CharField(max_length=10000, verbose_name='opisanie')),
                ('duration', models.CharField(max_length=100, verbose_name='hz')),
            ],
        ),
    ]
