# Generated by Django 5.1.3 on 2024-11-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_films'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
