# Generated by Django 5.1.3 on 2024-12-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pellegrim_alter_crypto_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='crypto',
        ),
        migrations.DeleteModel(
            name='Pellegrim',
        ),
    ]
